import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useEffect, useState} from 'react';
import Message from '../components/message';
import Yotsu from '../components/yotsu';
import Table from '../components/table'

export default function Home() {
  const [isOpening, setIsOpening] = useState(true);
  const [command, setCommand] = useState('$ ')

  const print = (e) => {
    if (e.key == 'Enter') {
      console.log('Enterが押された！')
      // だからここで一旦文字列の処理を行う
    }
  };

  const handleChangeCommad = (e) => {
    setCommand("$ "+e.target.value.replace(/\$/g, '').replace(/\ /g, ''))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>よつほーむ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>input</h1>
      <p>console.log(url);</p>

      <textarea
        className={styles.input}
        onKeyPress={print}
        onChange={handleChangeCommad}
        value={command}
      />
      
      {/* {isOpening && <Message/>}
      {!isOpening && <Yotsu/>}
      <Table></Table> */}
    </div>
  )
}
