import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useEffect, useState} from 'react';
import Message from '../components/message';
import Yotsu from '../components/yotsu';
import Table from '../components/table'

export default function Home() {
  const [value, setValue] = useState('$ ');

  const handleKeyPress = e => {
    if(e.key == 'Enter'){
      const splitedInputValue = e.target.value.split('\n');
      const line = splitedInputValue.slice(-1)[0].replace(/\$/, '').replace(/\s+/, '');
      splitedInputValue.push.apply(splitedInputValue, parse(line));
      setValue(splitedInputValue.join('\n'));
    }
  }

  const handleChangeValue = e => {
    const splitedInputValue = e.target.value.split('\n');
    const unfixedLast = splitedInputValue.pop();
    const fixedLast = '$ ' + unfixedLast.replace(/\$/g, '').replace(/\ /, '');  
    splitedInputValue.push(fixedLast);
    setValue(splitedInputValue.join('\n'));
  }

  const parse = (line: string) => {
    const splitedLine = line.split(/\s+/g);
    console.log(splitedLine);
    if(splitedLine.length == 0) return [''];
    if(splitedLine.length == 1 && splitedLine[0] == 'ls') return ['/MyHp', 'memo.txt', 'README.md'];
    if(splitedLine.length == 2 && splitedLine[0] == 'cd') return ['cd'];
    if(splitedLine.length == 2 && splitedLine[0] == 'cat') return ['cat'];
    return ['command not found: ' + line];
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>よつほーむ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>ls, cd, cat</h1>

      <textarea
        className={styles.input}
        onKeyPress={handleKeyPress} // keyを押したとき(変化は起こってない)
        onChange={handleChangeValue} // 改行が行われて変化が起こったとき
        value={value}
      />
    </div>
  )
}
